/**
 * Markdown summary for pasting into a PR or issue. Plain GitHub-flavoured
 * markdown (tables, <details>), kept well under GitHub's 65 536-character
 * comment limit by capping findings and evidence lists.
 */
import type { Report } from "./report";
import { metricRows, severityCounts } from "./summary";

export interface MarkdownOptions {
    maxFindings?: number;
    maxEvidencePerFinding?: number;
}

const SEVERITY_LABEL: Record<string, string> = { critical: "🔴 critical", warning: "🟠 warning", info: "🔵 info" };

/** Escapes text for a markdown table cell / inline context. */
export function mdEscape(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/[`*[\]<>]/g, (c) => `\\${c}`).replace(/\r?\n/g, " ");
}

function code(s: string): string {
    return `\`${s.replace(/`/g, "'")}\``;
}

function secs(s: number | null): string {
    return s === null ? "—" : `${s.toFixed(3)} s`;
}

export function renderMarkdown(report: Report, options: MarkdownOptions = {}): string {
    const maxFindings = options.maxFindings ?? 50;
    const maxEvidence = options.maxEvidencePerFinding ?? 8;
    const s = report.source;
    const out: string[] = [];
    out.push(`## ${mdEscape(report.title)}`, "");
    out.push(
        `**Session** ${s.sessionIds.map(code).join(", ") || "—"} · **events** ${s.exportedEvents}${s.exportedEvents !== s.totalEvents ? ` of ${s.totalEvents}` : ""} · **duration** ${secs(s.durationS)} · **range** ${mdEscape(s.range)}`,
    );
    out.push(`**Producers** ${s.producers.map(mdEscape).join(", ") || "—"}${s.synthetic ? " · ⚠️ synthetic data" : ""}`, "");

    out.push("### Summary metrics", "", "| Metric | Value |", "| --- | --- |");
    for (const r of metricRows(report.metrics)) {
        out.push(`| ${mdEscape(r.label)} | ${mdEscape(r.value)} |`);
    }
    out.push("");

    out.push(`### Diagnostics findings (${report.findings.length})`, "");
    if (report.findings.length === 0) {
        out.push("No findings.", "");
    } else {
        out.push(severityCounts(report.findings), "");
        out.push("| Severity | Kind | Time | Summary | Evidence |", "| --- | --- | --- | --- | --- |");
        const shown = report.findings.slice(0, maxFindings);
        for (const f of shown) {
            out.push(
                `| ${SEVERITY_LABEL[f.severity] ?? f.severity} | ${code(f.kind)} | ${secs(f.startRelS)}–${secs(f.endRelS)} | ${mdEscape(f.summary)} | ${f.evidence.length} |`,
            );
        }
        if (report.findings.length > shown.length) {
            out.push("", `_…and ${report.findings.length - shown.length} more findings (see the HTML or JSON export)._`);
        }
        out.push("", "<details><summary>Evidence events</summary>", "");
        for (const f of shown) {
            out.push(`- ${code(f.id)} (${f.provenance})`);
            for (const ev of f.evidence.slice(0, maxEvidence)) {
                out.push(`  - ${secs(ev.relS)} ${code(ev.eventType)} ${code(ev.eventId)}`);
            }
            if (f.evidence.length > maxEvidence) {
                out.push(`  - …${f.evidence.length - maxEvidence} more`);
            }
        }
        out.push("", "</details>", "");
    }

    const t = report.topology;
    out.push(`### Topology`, "", `${t.nodes.length} nodes, ${t.edges.length} edges.`);
    const kinds = new Map<string, number>();
    for (const n of t.nodes) {
        kinds.set(n.kind, (kinds.get(n.kind) ?? 0) + 1);
    }
    if (kinds.size > 0) {
        out.push(`Nodes by kind: ${[...kinds].map(([k, n]) => `${k} ${n}`).join(", ")}.`);
    }
    out.push("", `<sub>Generated by Sonder Observatory at ${report.generatedAt} (${report.format}).</sub>`, "");
    return out.join("\n");
}
