// Generates fixtures/synthetic-session.ndjson deterministically.
//
// SYNTHETIC DATA: every event is produced by this script, not by Sonder
// Runtime or Sonder-Inference. The producer carries `synthetic: true` and the
// UI labels any session containing such events as synthetic. The values are
// plausible shapes for exercising the viewer, not measurements of a model.
//
// Usage: node scripts/generate-fixture.mjs [output-path]
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : resolve(here, "..", "fixtures/synthetic-session.ndjson");

// Mulberry32: tiny seeded PRNG so the fixture is reproducible.
function rng(seed) {
    let a = seed >>> 0;
    return () => {
        a = (a + 0x6d2b79f5) >>> 0;
        let t = a;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}
const rand = rng(20260926);
const between = (lo, hi) => lo + Math.floor(rand() * (hi - lo + 1));

const SESSION = "ses_synthetic_0001";
const RUN = "run_synthetic_0001";
const MODEL = "mdl_synthetic_7b_q4";
const DEVICE = "dev_gpu0";
const MONO_BASE_NS = 1_000_000_000;
const WALL_BASE_MS = Date.parse("2026-09-26T08:00:00.000Z");
const PRODUCER = {
    name: "sonder-observatory-synthetic-fixture",
    version: "0.1.0",
    node_id: "fixture",
    synthetic: true,
};

const drafts = [];
function emit(ms, eventType, fields = {}, attributes = {}) {
    drafts.push({ ms, order: drafts.length, eventType, fields, attributes });
}

// --- session / model lifecycle -------------------------------------------
emit(0, "session.started", {}, {
    synthetic: true,
    text_capture: "none",
    note: "Synthetic fixture generated by scripts/generate-fixture.mjs; not model telemetry.",
    capabilities: ["requests", "tokens", "agents", "tools", "device.memory"],
});
emit(10, "model.load.started", { model_instance_id: MODEL, device_id: DEVICE }, {
    model: "synthetic-7b", quantization: "q4",
});
emit(780, "model.load.completed", { model_instance_id: MODEL, device_id: DEVICE }, {
    load_ms: 770,
});
emit(900, "agent.spawned", { agent_id: "agt_owner" }, { role: "owner" });
emit(905, "agent.started", { agent_id: "agt_owner" }, { role: "owner" });
emit(910, "route.selected", { agent_id: "agt_owner", model_instance_id: MODEL }, {
    reason: "default-route",
});

// --- requests ---------------------------------------------------------------
const agentFor = (i) => (i < 2 ? "agt_owner" : i < 6 ? "agt_worker_1" : i < 8 ? "agt_critic" : "agt_owner");
let t = 1000;
let tool = 0;
const activity = []; // [startMs, endMs] for resource shaping
for (let i = 0; i < 10; i += 1) {
    const req = `req_${String(i + 1).padStart(3, "0")}`;
    const agent = agentFor(i);
    const base = { run_id: RUN, request_id: req, agent_id: agent, model_instance_id: MODEL };

    if (i === 2) {
        emit(t - 60, "agent.spawned", { run_id: RUN, agent_id: "agt_worker_1" }, { role: "worker", parent: "agt_owner" });
        emit(t - 40, "agent.started", { run_id: RUN, agent_id: "agt_worker_1" }, { role: "worker" });
        emit(t - 30, "route.selected", { run_id: RUN, agent_id: "agt_worker_1", model_instance_id: MODEL }, { reason: "worker-default" });
    }
    if (i === 6) {
        emit(t - 60, "agent.spawned", { run_id: RUN, agent_id: "agt_critic" }, { role: "critic", parent: "agt_owner" });
        emit(t - 40, "agent.started", { run_id: RUN, agent_id: "agt_critic" }, { role: "critic" });
    }

    const promptTokens = between(300, 1800);
    emit(t, "request.queued", base, { prompt_tokens: promptTokens });
    const start = t + between(5, 40);
    emit(start, "request.started", base, { prompt_tokens: promptTokens });
    emit(start + 2, "scheduler.admitted", { ...base, device_id: DEVICE }, { queue_depth: between(0, 2) });
    emit(start + 4, "inference.prefill.started", { ...base, device_id: DEVICE }, { prompt_tokens: promptTokens });
    const prefillMs = Math.round(promptTokens / between(6, 10));
    const firstToken = start + 4 + prefillMs;
    emit(firstToken - 1, "inference.prefill.completed", { ...base, device_id: DEVICE }, {
        prompt_tokens: promptTokens, prefill_ms: prefillMs,
    });
    emit(firstToken, "inference.decode.started", { ...base, device_id: DEVICE }, {});

    const failing = i === 8;
    const nTokens = failing ? 14 : between(24, 48);
    let tt = firstToken;
    for (let k = 0; k < nTokens; k += 1) {
        tt += between(18, 38) + (i >= 7 ? between(0, 20) : 0); // slower under pressure
        emit(tt, "inference.token.generated", { ...base, device_id: DEVICE }, {
            position: promptTokens + k, text_capture: "none", token_text: null,
        });
        if (i === 3 && k === 10) {
            tool += 1;
            emit(tt + 1, "tool.called", base, { tool_call_id: `tc_${tool}`, tool: "synthetic.search", args: "[redacted]" });
            emit(tt + 180, "tool.completed", base, { tool_call_id: `tc_${tool}`, duration_ms: 179, result: "[redacted]" });
            tt += 185;
        }
        if (i === 5 && k === 8) {
            tool += 1;
            emit(tt + 1, "tool.called", base, { tool_call_id: `tc_${tool}`, tool: "synthetic.fetch", args: "[redacted]" });
            emit(tt + 400, "tool.failed", base, { tool_call_id: `tc_${tool}`, error: "synthetic timeout", duration_ms: 399 });
            emit(tt + 405, "retry.scheduled", base, { tool_call_id: `tc_${tool}`, attempt: 2, backoff_ms: 100 });
            tool += 1;
            emit(tt + 510, "tool.called", base, { tool_call_id: `tc_${tool}`, tool: "synthetic.fetch", args: "[redacted]", attempt: 2 });
            emit(tt + 690, "tool.completed", base, { tool_call_id: `tc_${tool}`, duration_ms: 180, result: "[redacted]" });
            tt += 700;
        }
        if (failing && k === 9) {
            emit(tt + 2, "kv.pressure", { ...base, device_id: DEVICE }, { occupancy: 0.96, action: "evict-candidates" });
            emit(tt + 4, "guard.budget_pressure", base, { budget: "context", used_fraction: 0.93 });
        }
    }
    if (failing) {
        emit(tt + 250, "inference.decode.completed", { ...base, device_id: DEVICE }, { generated_tokens: nTokens, stop: "error" });
        emit(tt + 252, "request.failed", base, { error: "synthetic decode timeout", generated_tokens: nTokens });
        emit(tt + 260, "telemetry.dropped", { run_id: RUN }, { dropped_count: 3, reason: "synthetic producer queue full" });
        tt += 260;
    } else {
        emit(tt + 3, "inference.decode.completed", { ...base, device_id: DEVICE }, { generated_tokens: nTokens, stop: "eos" });
        emit(tt + 5, "request.completed", base, { generated_tokens: nTokens });
        tt += 5;
    }
    activity.push([start, tt, i]);

    if (i === 5) {
        emit(tt + 20, "agent.completed", { run_id: RUN, agent_id: "agt_worker_1" }, { role: "worker" });
    }
    if (i === 7) {
        emit(tt + 20, "agent.completed", { run_id: RUN, agent_id: "agt_critic" }, { role: "critic" });
    }
    t = tt + between(150, 450);
}
const endMs = t + 200;
emit(endMs - 20, "agent.completed", { run_id: RUN, agent_id: "agt_owner" }, { role: "owner" });

// --- device samples every 250 ms -------------------------------------------
const TOTAL = 12 * 1024 ** 3;
for (let ms = 250; ms < endMs; ms += 250) {
    const active = activity.find(([a, b]) => ms >= a && ms <= b);
    const idx = active ? active[2] : -1;
    const modelBytes = ms >= 780 ? 4.4 * 1024 ** 3 : (ms / 780) * 4.4 * 1024 ** 3;
    const kvBytes = active ? (0.8 + idx * 0.62) * 1024 ** 3 : 0.3 * 1024 ** 3;
    const used = Math.round(1.1 * 1024 ** 3 + modelBytes + kvBytes);
    emit(ms, "device.memory.sample", { device_id: DEVICE }, {
        used_bytes: Math.min(used, TOTAL), total_bytes: TOTAL, kind: "vram",
    });
    emit(ms, "device.compute.sample", { device_id: DEVICE }, {
        utilization: active ? Math.round((0.55 + rand() * 0.4) * 100) / 100 : Math.round(rand() * 8) / 100,
    });
}
emit(endMs, "session.ended", {}, { reason: "fixture-complete" });

// --- finalize: order, sequence, ids, clocks --------------------------------
drafts.sort((a, b) => a.ms - b.ms || a.order - b.order);
const lines = drafts.map((d, seq) => {
    const monoNs = MONO_BASE_NS + d.ms * 1_000_000;
    const event = {
        schema: "sonder.observatory.event/1",
        event_id: `evt_syn_${String(seq + 1).padStart(6, "0")}`,
        sequence: seq,
        event_type: d.eventType,
        wall_time: new Date(WALL_BASE_MS + d.ms).toISOString(),
        mono_ns: monoNs,
        session_id: SESSION,
        run_id: d.fields.run_id ?? null,
        request_id: d.fields.request_id ?? null,
        agent_id: d.fields.agent_id ?? null,
        model_instance_id: d.fields.model_instance_id ?? null,
        device_id: d.fields.device_id ?? null,
        producer: PRODUCER,
        sampling: { level: "standard", sampled: true },
        attributes: d.attributes,
    };
    return JSON.stringify(event);
});
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
console.log(`wrote ${lines.length} synthetic events to ${outPath}`);
